# CI de nível 1: Disparo manual de 1 click
# nome do nosso 'pipeline'
name: 'Execução Manual'
# Regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch
on:
  workflow_dispatch:

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    # máquina que o job vai executar
    runs-on: ubuntu-latest
    # passos so script do build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências 
        run: yarn
      
      # instalação do Playwrigth
      - name: Instalando o Playwright
        run: yarn playwright 

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e
